/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_proyecto;

import com.google.gson.Gson;
import com.jtattoo.plaf.noire.NoireLookAndFeel;
import com.mycompany.tap_proyecto.Clases.Usuario;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author chuy-
 */
public class FormInicio extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios=new ArrayList();
    String archivoUsuarios="Users example path";
    public FormInicio() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldContra = new javax.swing.JPasswordField();
        labelNoUsuarios = new javax.swing.JLabel();
        buttonAcceder = new javax.swing.JButton();
        buttonCrearUsuario = new javax.swing.JButton();
        buttonVerContra = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuarios");

        textFieldNombre.setBackground(new java.awt.Color(0,0,0,1));
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldNombre.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        textFieldContra.setBackground(new java.awt.Color(0,0,0,1));
        textFieldContra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldContra.setBorder(null);
        textFieldContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldContraKeyPressed(evt);
            }
        });

        labelNoUsuarios.setForeground(new java.awt.Color(255, 51, 51));
        labelNoUsuarios.setText("No existen usuarios");

        buttonAcceder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAcceder.setText("Acceder");
        buttonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccederActionPerformed(evt);
            }
        });

        buttonCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCrearUsuario.setText("Crear usuario");
        buttonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearUsuarioActionPerformed(evt);
            }
        });

        buttonVerContra.setIcon(new javax.swing.ImageIcon("C:\\Users\\chuy-\\OneDrive\\Escritorio\\Universidad\\4 Semestre\\Unidad 1\\TAP_PROYECTO\\src\\main\\java\\Imagenes\\dejarDeVerContra.png")); // NOI18N
        buttonVerContra.setBorder(null);
        buttonVerContra.setContentAreaFilled(false);
        buttonVerContra.setDisabledIcon(null);
        buttonVerContra.setFocusPainted(false);
        buttonVerContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldContra, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonVerContra)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelNoUsuarios)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelNoUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        usuarios.clear();
        cargarUsuarios();
        if(usuarios.size()>0)labelNoUsuarios.setVisible(false);
        else labelNoUsuarios.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        usuarios.clear();
        cargarUsuarios();
    }//GEN-LAST:event_formWindowGainedFocus

    private void buttonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearUsuarioActionPerformed
        new FormCrearUsuario().setVisible(true);
    }//GEN-LAST:event_buttonCrearUsuarioActionPerformed

    private void buttonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccederActionPerformed
        boolean comprobador=false;
        for(Usuario u:usuarios){
            if(u.getNombre().equals(textFieldNombre.getText())&&u.getContra().equals(textFieldContra.getText())){
                new FormPrincipal().setVisible(true);
                comprobador=true;
                dispose();
            }
        }
        if(!comprobador)JOptionPane.showMessageDialog(null, "Los datos son incorrectos");
    }//GEN-LAST:event_buttonAccederActionPerformed

    private void buttonVerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerContraActionPerformed
        if(buttonVerContra.isSelected()){
            textFieldContra.setEchoChar((char)0);
            buttonVerContra.setIcon(new javax.swing.ImageIcon("C:\\Users\\chuy-\\OneDrive\\Escritorio\\Universidad\\4 Semestre\\Unidad 1\\TAP_PROYECTO\\src\\main\\java\\Imagenes\\verContra.png"));
        }
        else{
            textFieldContra.setEchoChar('*');
            buttonVerContra.setIcon(new javax.swing.ImageIcon("C:\\Users\\chuy-\\OneDrive\\Escritorio\\Universidad\\4 Semestre\\Unidad 1\\TAP_PROYECTO\\src\\main\\java\\Imagenes\\dejarDeVerContra.png"));
        }
    }//GEN-LAST:event_buttonVerContraActionPerformed

    private void textFieldContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldContraKeyPressed
        if(evt.getKeyChar()==evt.VK_ENTER){
            buttonAcceder.doClick();
        }
    }//GEN-LAST:event_textFieldContraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcceder;
    private javax.swing.JButton buttonCrearUsuario;
    private javax.swing.JToggleButton buttonVerContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelNoUsuarios;
    private javax.swing.JPasswordField textFieldContra;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarUsuarios() {
        try {
            BufferedReader br = new BufferedReader(new FileReader(archivoUsuarios));
            String lectura = null;
            while( (lectura = br.readLine()) != null ) {
                JSONObject jsonObject=(JSONObject)JSONValue.parse(lectura);
                Gson gson=new Gson();
                Usuario u=gson.fromJson(jsonObject.toJSONString(), Usuario.class);
                System.out.println("Usuario leido:" +u.getNombre());
                usuarios.add(u);
            }
            br.close();
        
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
